### ISSUE TITLE
f30k evaluation

### ISSUE THREAD

**Issue by abueidvchow** [ZhangXu0963/NPC#3]
Hello, I encountered a problem when using the F30K dataset for evaluation, as shown in the figure below. I want to know how to solve it.Thank you!
![图片](https://github.com/ZhangXu0963/NPC/assets/55395215/e07d335d-b042-4bb3-a33b-5ca954ee93ec)

**Comment by ZhangXu0963** [comment]
Maybe you can follow steps below to find the root cause of the error.
1. You can check the parameters ‘--dataset_root’ and ’--dataset‘ in 'params.py' to make sure the test dataset is correct.
2. You can check the 'test_length' in 'line67, main_NPC.py', it should be 5000 (as shown in the fig below).
![屏幕截图 2024-04-19 154316](https://github.com/ZhangXu0963/NPC/assets/67301658/fd7cacfb-bcf4-456b-ab90-9cfa7f4760e8)
3. You can check the shape of 'label' and 'i2t_rank_matrix' in 'line 112, eval.py', they should all be '[1000, 5000]' (as shown below)
![屏幕截图 2024-04-19 154329](https://github.com/ZhangXu0963/NPC/assets/67301658/2eb2388b-d1e4-4d90-9600-d10368821d31)
